import { forwardRef } from 'react';

interface ReportTemplateProps {
  projectName: string;
  clientName: string;
  image: string | null;
  date: string;
}

export const ReportTemplate = forwardRef<HTMLDivElement, ReportTemplateProps>(
  ({ projectName, clientName, image, date }, ref) => {
    return (
      <div
        ref={ref}
        className="bg-white p-8 flex flex-col"
        style={{
          width: '210mm', // A4 width
          minHeight: '297mm', // A4 height
          margin: '0 auto',
        }}
      >
        {/* Header */}
        <div className="border-b-2 border-gray-800 pb-4 mb-8">
          <div className="flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Vastu Analysis Report</h1>
              <p className="text-gray-500 mt-1">Generated by Vastu App</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600">Date: {date}</p>
            </div>
          </div>
        </div>

        {/* Project Details */}
        <div className="grid grid-cols-2 gap-8 mb-8 bg-gray-50 p-6 rounded-lg">
          <div>
            <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider">Project Name</h3>
            <p className="text-xl font-medium text-gray-900 mt-1">{projectName || 'Untitled Project'}</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider">Client Name</h3>
            <p className="text-xl font-medium text-gray-900 mt-1">{clientName || 'N/A'}</p>
          </div>
        </div>

        {/* Floorplan Image */}
        <div className="flex-1 flex flex-col items-center justify-center border-2 border-gray-100 rounded-lg p-4 mb-8 bg-white">
          {image ? (
            <img
              src={image}
              alt="Floorplan Analysis"
              className="max-w-full max-h-[150mm] object-contain"
            />
          ) : (
            <div className="text-gray-400 italic">No floorplan image available</div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-auto pt-8 border-t border-gray-200 text-center text-sm text-gray-500">
          <p>&copy; {new Date().getFullYear()} Vastu Agency. All rights reserved.</p>
        </div>
      </div>
    );
  }
);

ReportTemplate.displayName = 'ReportTemplate';
